- hosts: fortigates
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
    - name: Get the current system config
      fortinet.fortios.fortios_system_config:
        access_token: "{{ ansible_password }}"
        state: "gathered"
      register: config_data

    - name: Backup config to a file
      copy:
        content: "{{ config_data }}"
        dest: "/path/to/backup.conf"

