- name: Backup config
  hosts: localhost
  tasks:
    - name: Backup configuration
      uri:
        url: "https://172.16.22.253:56443/api/v2/monitor/system/config/backup"
        method: POST
        body_format: json
        body:
          access_token: "jr68h84c898myzjbggqs84x8Q5ffcQ"
          scope: "global"
          vdom: "Global"
        validate_certs: no
        headers:
          Content-Type: "application/json"
      register: response

    - name: Save configuration to file
      copy:
        content: "{{ response.content }}"
        dest: "/tmp/backup.conf"
